title: Chinmay P. RELE
description: An online version of a CV.
theme: just-the-docs

url: https://chinmayprele.github.io


plugins:
  - jekyll-default-layout

color_scheme: dark  # Color scheme supports "light" (default) and "dark"
