title: Chinmay P. RELE
description: An online version of a CV.
theme: just-the-docs

url: https://chinmayprele.github.io

color_scheme: light  # Color scheme supports "light" (default) and "dark"

kramdown:
  input: Kramdown
